Treasure Hunters: Player Class Reference
Player Class Reference
Player.
#include <Player.hpp>
Public Member Functions
Player ()
Player constructor.
~Player ()
Player destructor.
void moveUp ()
Move player to 'up' direction.
void moveDown ()
Move player to 'down' direction.
void moveLeft ()
Move player to 'left' direction.
void moveRight ()
Move player to 'right' direction.
void attack ()
Perform an attack.
void defend ()
Put player in defense stance.
void pause ()
Pause the game hope the player is not dying
void update (sf::RenderWindow &window, sf::Time frame_time)
Update player position in the window.
void setMovementX (float value)
Sets the player movement in 'x' direction.
void setMovementY (float value)
Sets the player movement in 'y' direction.
void updateMovementX (float value)
Updates the player movement in 'x' direction.
void updateMovementY (float value)
Updates the player movement in 'y' direction.
Player & self ()
Get an itself reference.
virtual void draw (sf::RenderTarget &target, sf::RenderStates states) const
Detailed Description
Player.
This class represents a player in the game
Definition at line 14 of file Player.hpp.
Member Function Documentation
void Player::attack ()
Perform an attack.
Todo:
Implements attack
Todo:
Implements attack
Definition at line 127 of file Player.cpp.
Referenced by AttackCommand::execute().
                     {
 }
void Player::defend ()
Put player in defense stance.
Todo:
Implements defense
Todo:
Implements defense
Definition at line 135 of file Player.cpp.
Referenced by DefendCommand::execute().
                     {
 }
void Player::draw (sf::RenderTarget & target, sf::RenderStates states) const virtual
See also
sf::Drawable::draw
Definition at line 28 of file Player.cpp.
{
     target.draw(player, states);
 }
void Player::pause ()
Pause the game hope the player is not dying
Todo:
Implements game pause
Todo:
Implements game pause
Definition at line 143 of file Player.cpp.
Referenced by StartCommand::execute().
                    {
 }
Player & Player::self ()
Get an itself reference.
Returns
A reference to itself
Definition at line 37 of file Player.cpp.
                      {
     return *this;
 }
void Player::setMovementX (float value)
Sets the player movement in 'x' direction.
Parameters
[in] value The movement speed in 'x' direction < 0 -> moving left = 0 -> wait/stop > 0 -> moving right
Definition at line 50 of file Player.cpp.
Referenced by moveLeft(), and moveRight().
{
     movement.x = value;
 }
void Player::setMovementY (float value)
Sets the player movement in 'y' direction.
[in] value The movement speed in 'y' direction < 0 -> moving down = 0 -> wait/stop > 0 -> moving up
Definition at line 62 of file Player.cpp.
Referenced by moveDown(), and moveUp().
{
     movement.y = value;
 }
void Player::update (sf::RenderWindow & window, sf::Time frame_time)
Update player position in the window.
Parameters
[in] window A reference to the game window
[in] frame_time The game clock to avoid lag
Definition at line 152 of file Player.cpp.
Referenced by World::update().
{
     boundary.x = window.getSize().x;
     boundary.y = window.getSize().y;
     movement.x = 0.f;
     movement.y = 0.f;
     input_handler.handleInput(self());
     player.move(movement * frame_time.asSeconds());
 }
void Player::updateMovementX (float value)
Updates the player movement in 'x' direction.
Parameters
[in] value The factor value to modify the player speed in 'x' direction
Definition at line 72 of file Player.cpp.
{
     movement.x *= value;
 }
void Player::updateMovementY (float value)
Updates the player movement in 'y' direction.
Parameters
[in] value The factor value to modify the player speed in 'y' direction
Definition at line 82 of file Player.cpp.
{
     movement.y *= value;
 }
The documentation for this class was generated from the following files:
include/Player.hpp
Player.cpp