Treasure Hunters: VideoSettings Class Reference
VideoSettings Class Reference
VideoSettings.
#include <VideoSettings.hpp>
Public Member Functions
VideoSettings ()
VideoSettings constructor.
~VideoSettings ()
VideoSettings destructor.
const sf::Vector2i getWindowDimension ()
Get the window dimension.
void setWindowDimension (int width, int height)
Set the window dimension.
const unsigned long getWindowStyle ()
Get the window style.
void setWindowStyle (unsigned long style)
Set the window style.
const sf::Vector2i getWindowPosition ()
Get the window position, where window will start to be rendered.
const int getFramerateLimit ()
Get the window framerate limit.
Detailed Description
VideoSettings.
The class VideoSettings is used to configure a bunch of video features
Definition at line 13 of file VideoSettings.hpp.
Member Function Documentation
const int VideoSettings::getFramerateLimit ()
Get the window framerate limit.
Returns
The window framerate limit
Definition at line 71 of file VideoSettings.cpp.
Referenced by Game::run().
{
     return framerate_limit;
 }
const sf::Vector2i VideoSettings::getWindowDimension ()
Get the window dimension.
Returns
The configure window dimension
Definition at line 22 of file VideoSettings.cpp.
Referenced by Game::run(), and World::World().
{
     return window_dimension;
 }
const sf::Vector2i VideoSettings::getWindowPosition ()
Get the window position, where window will start to be rendered.
Returns
The window position
Definition at line 62 of file VideoSettings.cpp.
{
     return window_position;
 }
const unsigned long VideoSettings::getWindowStyle ()
Get the window style.
See also
sf::Style
Returns
The window style code
Definition at line 44 of file VideoSettings.cpp.
Referenced by Game::run().
{
     return window_style;
 }
void VideoSettings::setWindowDimension (int width, int height)
Set the window dimension.
Parameters
[in] width The window width dimension
[in] height The window height dimension
Definition at line 32 of file VideoSettings.cpp.
{
     window_dimension.x = width;
     window_dimension.y = height;
 }
void VideoSettings::setWindowStyle (unsigned long style)
Set the window style.
Parameters
[in] style Window style code
Definition at line 53 of file VideoSettings.cpp.
{
     window_style = style;
 }
The documentation for this class was generated from the following files:
include/VideoSettings.hpp
VideoSettings.cpp