Treasure Hunters: World Class Reference
World Class Reference
World.
#include <World.hpp>
Public Member Functions
World ()
World constructor.
virtual ~World ()
World destructor.
void draw (sf::RenderWindow &window)
Draw the world elements in window.
const Terrain & getTile (int row, int column) const
Get the tile from the grid.
void loadResources ()
Load the resources used in the world.
void createRandomWorld ()
Create random tiles for each cell in the grid.
void update (sf::RenderWindow &window, sf::Time frame_time)
Update game elements in the world.
Detailed Description
World.
One renderer to render them all
Definition at line 18 of file World.hpp.
Member Function Documentation
void World::draw (sf::RenderWindow & window)
Draw the world elements in window.
Parameters
[in] window Where the game elements will be drawn
Definition at line 30 of file World.cpp.
Referenced by Game::render(), and ~World().
{
     for (int i = 0; i < rows; i++) {
         for (int j = 0; j < columns; j++) {
             window.draw(getTile(i, j));
         }
     }
     window.draw(player);
 }
const Terrain & World::getTile (int row, int column) const
Get the tile from the grid.
Parameters
[in] row The grid row
[in] column The grid column
Returns
Get the tile from the given position
Definition at line 48 of file World.cpp.
Referenced by draw(), and ~World().
{
     tiles[row][column]->setPosition(
         (row * kBlockSize) + padding_width,
         (column * kBlockSize) + padding_height);
     return *tiles[row][column];
 }
void World::update (sf::RenderWindow & window, sf::Time frame_time)
Update game elements in the world.
Parameters
[in] window The game window
[in] frame_time The game clock shared with all resources
Definition at line 126 of file World.cpp.
Referenced by Game::play(), and ~World().
{
     player.update(window, frame_time);
 }
The documentation for this class was generated from the following files:
include/World.hpp
World.cpp